POST http://localhost:3000/api/games/
Content-Type: application/json

{
    "name": "PeriodicPairs",
    "description": "A quiz game about the periodic table.",
    "url": "/static-games/PeriodicPairs/index.html",
    "thumbnail": "/static-games/PeriodicPairs/game1.png",
    "how_to_play": "Type the full name of the chemical element that matches the symbol shown on the screen and click Submit."
}