PUT http://localhost:3000/api/users/1/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbGwiLCJpZCI6NjAsImlhdCI6MTc2NjQxNDY5NH0.Yzd76FKSBgZFStJWM4UIdIHPjbK3vLISm6h40F51dZA
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="bulba.jpg"
Content-Type: text/plain

< /Users/yourname/Desktop/bulba.jpg
--boundary--
